version: "3.12.8"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: ${MONGO_URI}
      FLASK_ENV: ${FLASK_ENV}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
